"""Extended-baseline backtest — wide econometric comparison panel.

Runs the v0.4 extended baselines (HAR-RV, CAViaR-SAV, MS-2-state,
FIGARCH(1,d,0), SV-AR1, Bivariate VAR-GARCH(BTC+ETH)) alongside the v0.3
WGeo-GARCH-Ens anchor on BTC at horizons {1, 5, 21}. Writes a per-symbol
comparison table to `docs/RESULTS_EXTENDED.md`.

The headline `docs/RESULTS_LONG.md` panel (Static/RW/HS/GARCH/WGeo
families across BTC/ETH/SOL/BNB) remains the production result of record.
This extended panel narrows the focus to BTC so we can include the
heavier-to-fit baselines (FIGARCH, CAViaR per-quantile) in finite time,
while comparing the WGeo family against the *named* econometric methods
people cite for distributional volatility forecasting.

To make the multivariate baseline ETH-aware while still using the same
walk-forward harness, the BivariateVARGarch class is constructed *outside*
the harness with the full BTC + ETH series and locates the matching ETH
window from the BTC suffix passed to `fit`.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from wbtc.backtest import load_returns
from wbtc.forecasters import (
    CAViaRSAV,
    FIGARCH,
    HARRV,
    BivariateVARGarch,
    GarchStudentT,
    MarkovSwitching2,
    StochasticVolatilityAR1,
    WGeoGarchEnsemble,
)
from wbtc.long_horizon import (
    by_regime,
    by_year,
    overall_summary,
    pairwise_dm,
    run_long_horizon,
    tag_regimes,
)

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
RESULTS = ROOT / "results"
RESULTS.mkdir(exist_ok=True)
DOC = ROOT / "docs" / "RESULTS_EXTENDED.md"

SYMBOL = "BTC/USDT"
EXOG_SYMBOL = "ETH/USDT"
HORIZONS = [1, 5, 21]
BURN_IN = 730
WGEO_WINDOW = 90
WGEO_LOOKBACK = 20


def slug(symbol: str) -> str:
    return symbol.lower().replace("/", "")


def build_methods(btc_full: np.ndarray, eth_full: np.ndarray) -> dict:
    """Method factory dict. The bivariate baseline closes over the full ETH
    series so the walk-forward harness can still call `fac()` with no args."""

    def make_bvar():
        return BivariateVARGarch(full_target=btc_full, full_exog=eth_full)

    return {
        # v0.3 anchor for relative comparison
        "WGeo-GARCH-Ens": lambda: WGeoGarchEnsemble(
            window=WGEO_WINDOW, lookback=WGEO_LOOKBACK
        ),
        # textbook benchmark
        "GARCH-t": GarchStudentT,
        # v0.4 extended baselines
        "HAR-RV": HARRV,
        "CAViaR-SAV": lambda: CAViaRSAV(n_starts=1),
        "MS-Normal-2": MarkovSwitching2,
        "FIGARCH(1,d,0)": FIGARCH,
        "SV-AR1": StochasticVolatilityAR1,
        "BVAR-GARCH(BTC,ETH)": make_bvar,
    }


def align_series(
    btc: pd.DataFrame, eth: pd.DataFrame
) -> tuple[pd.DataFrame, np.ndarray]:
    """Return (btc_inner_aligned_to_common_dates, eth_returns_aligned)."""
    eth_renamed = eth[["ts", "r"]].rename(columns={"r": "r_eth"})
    merged = btc.merge(eth_renamed, on="ts", how="inner").reset_index(drop=True)
    return merged.drop(columns=["r_eth"]), merged["r_eth"].to_numpy()


def fmt_pct_diff(a: float, b: float) -> str:
    if b == 0:
        return "—"
    return f"{(a - b) / b * 100:+.1f}%"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--parallel",
        type=int,
        default=1,
        help="Number of worker processes for the method loop (1=sequential, -1=all cores).",
    )
    parser.add_argument(
        "--stride",
        type=int,
        default=1,
        help=(
            "Refit-every-K-steps stride. stride=1 (default) is the conservative "
            "refit-every-step protocol used by the headline RESULTS_LONG.md; "
            "stride=5 is the standard 'weekly refit' approximation that cuts "
            "runtime ~5x with negligible CRPS impact at h>=5."
        ),
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=DOC,
        help=f"Output markdown path (default: {DOC}).",
    )
    args = parser.parse_args(argv)

    btc = load_returns(DATA / f"{slug(SYMBOL)}_1d.parquet")
    eth = load_returns(DATA / f"{slug(EXOG_SYMBOL)}_1d.parquet")
    aligned_df, eth_returns = align_series(btc, eth)
    btc_returns = aligned_df["r"].to_numpy()
    timestamps = aligned_df["ts"]
    regime_tags = tag_regimes(btc_returns, lookback=60)

    methods = build_methods(btc_returns, eth_returns)

    md = [
        "# Extended Baseline Comparison — BTC distributional forecasts",
        "",
        f"_Generated by `scripts/run_extended_baselines.py` on {pd.Timestamp.now('UTC').date()}_",
        "",
        "**Why this report.** `docs/RESULTS_LONG.md` benchmarks the WGeo family",
        "against light textbook baselines (Static / RW / HS-Bootstrap / GARCH-N /",
        "GARCH-t / GJR-GARCH-t) on four assets and is the production result of",
        "record. This file extends the comparison to *named econometric methods*",
        "from adjacent families that practitioners ask about: HAR-RV (Corsi),",
        "CAViaR (Engle-Manganelli), Markov-switching / MS-GARCH, FIGARCH",
        "(long-memory), Stochastic Volatility (Kalman QML), and a bivariate",
        "VAR+GARCH that uses ETH as an additional information source.",
        "",
        "Restricted to BTC/USDT so the heavier per-step fits (FIGARCH MLE,",
        "CAViaR per-quantile QR) complete in tractable time. Walk-forward,",
        "burn-in 730 days, CRPS scoring on a 30-point grid — identical",
        "protocol to `RESULTS_LONG.md`.",
        "",
        f"_{len(aligned_df)} days from {aligned_df['ts'].min().date()} to {aligned_df['ts'].max().date()} "
        f"(BTC ∩ ETH common dates)._",
        "",
    ]

    headline_rows: list[dict] = []

    for h in HORIZONS:
        print(
            f"\n[extended] {SYMBOL} h={h}  parallel={args.parallel} stride={args.stride}"
        )
        t0 = time.time()
        res = run_long_horizon(
            btc_returns,
            timestamps,
            methods,
            burn_in=BURN_IN,
            horizon=h,
            K=30,
            n_jobs=args.parallel,
            stride=args.stride,
        )
        elapsed = time.time() - t0
        print(f"  done in {elapsed / 60:.1f} min")

        out = {name: losses.tolist() for name, losses in res.aligned_losses.items()}
        out["t_idx"] = res.aligned_idx
        (RESULTS / f"extended_btc_h{h}.json").write_text(json.dumps(out))

        summary = overall_summary(res, horizon=h)
        yr = by_year(res, timestamps)
        reg = by_regime(res, regime_tags)
        _, dm_p = pairwise_dm(res, horizon=h)

        anchor = "WGeo-GARCH-Ens"
        ranked = summary["mean_crps"].sort_values()
        best_name = str(ranked.index[0])
        for name in summary.index:
            if name == anchor:
                continue
            headline_rows.append(
                {
                    "h": h,
                    "method": name,
                    "mean_crps": float(summary.loc[name, "mean_crps"]),
                    "vs_anchor": fmt_pct_diff(
                        float(summary.loc[name, "mean_crps"]),
                        float(summary.loc[anchor, "mean_crps"]),
                    ),
                    "dm_p_vs_anchor": float(dm_p.loc[name, anchor]),
                }
            )
        headline_rows.append(
            {
                "h": h,
                "method": anchor,
                "mean_crps": float(summary.loc[anchor, "mean_crps"]),
                "vs_anchor": "0.0%",
                "dm_p_vs_anchor": 1.0,
            }
        )

        md += [
            f"### Horizon h = {h} day(s)  —  best: **{best_name}**",
            "",
            "**Overall mean CRPS (bootstrap 95% CI):**",
            "",
            summary.map(
                lambda x: f"{x:.6f}" if isinstance(x, float) else x
            ).to_markdown(),
            "",
            "**Per-year mean CRPS:**",
            "",
            yr.map(lambda x: f"{x:.5f}" if isinstance(x, float) else x).to_markdown(),
            "",
            "**Per-regime mean CRPS:**",
            "",
            reg.map(lambda x: f"{x:.5f}" if isinstance(x, float) else x).to_markdown(),
            "",
            "**Diebold-Mariano p-values vs WGeo-GARCH-Ens** "
            "(p < 0.05 favours WGeo-GARCH-Ens):",
            "",
            dm_p[anchor].round(4).to_frame(name="p_vs_WGeo-GARCH-Ens").to_markdown(),
            "",
        ]

        fig, ax = plt.subplots(figsize=(11, 4.5))
        xs = np.arange(len(res.aligned_idx))
        for name, losses in res.aligned_losses.items():
            ax.plot(xs, np.cumsum(losses), label=name, lw=1.0)
        ax.set_title(
            f"Cumulative CRPS — {SYMBOL} h={h}d ({len(xs)} test steps) — extended panel"
        )
        ax.set_xlabel("step")
        ax.set_ylabel("cumulative CRPS")
        ax.legend(loc="upper left", fontsize=7, ncols=2)
        ax.grid(alpha=0.3)
        fig.tight_layout()
        png = RESULTS / f"extended_cum_crps_btc_h{h}.png"
        fig.savefig(png, dpi=110)
        plt.close(fig)
        md += [f"![cumulative CRPS](../results/{png.name})", ""]

    # headline block at top
    headline_df = pd.DataFrame(headline_rows).sort_values(["h", "mean_crps"])
    md = (
        md[:5]
        + [
            "## Headline table — every method, every horizon",
            "",
            "Lower `mean_crps` is better. `vs_anchor` is the percentage gap to",
            "`WGeo-GARCH-Ens` (negative = the named baseline beats the anchor).",
            "`dm_p_vs_anchor` is the Diebold-Mariano p-value comparing that",
            "method's per-step loss series to the anchor's; small p favours the",
            "anchor (because the anchor's mean is lower by construction at most",
            "horizons here).",
            "",
            headline_df.assign(
                mean_crps=lambda d: d["mean_crps"].map(lambda x: f"{x:.6f}"),
                dm_p_vs_anchor=lambda d: d["dm_p_vs_anchor"].map(lambda x: f"{x:.4f}"),
            ).to_markdown(index=False),
            "",
        ]
        + md[5:]
    )

    args.out.write_text("\n".join(md))
    print(f"\n[extended] wrote {args.out}")
    print(json.dumps(headline_rows, indent=2, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
